
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayana Citra
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NamaMakanan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NamaMinuman = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        HargaMakanan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        HargaMinuman = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        SAVE = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        PRINT = new javax.swing.JButton();
        ORDER = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Engravers MT", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RESTO NEW MOON");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 30, 600, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 830, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel4.setText("Nama Makanan");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 120, 14);
        jPanel2.add(NamaMakanan);
        NamaMakanan.setBounds(10, 30, 220, 30);

        jLabel5.setText("Nama Minuman");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 70, 120, 14);
        jPanel2.add(NamaMinuman);
        NamaMinuman.setBounds(10, 90, 220, 30);

        jLabel6.setText("Harga Makanan");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 130, 120, 14);
        jPanel2.add(HargaMakanan);
        HargaMakanan.setBounds(10, 150, 220, 30);

        jLabel7.setText("Harga Minuman");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 190, 120, 14);
        jPanel2.add(HargaMinuman);
        HargaMinuman.setBounds(10, 210, 220, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 120, 240, 260);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        SAVE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        jPanel3.add(SAVE);
        SAVE.setBounds(10, 10, 80, 30);

        CLEAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        jPanel3.add(CLEAR);
        CLEAR.setBounds(100, 10, 80, 30);

        DELETE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel3.add(DELETE);
        DELETE.setBounds(190, 10, 80, 30);

        PRINT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PRINT.setText("PRINT");
        PRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINTActionPerformed(evt);
            }
        });
        jPanel3.add(PRINT);
        PRINT.setBounds(280, 10, 80, 30);

        ORDER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ORDER.setText("ORDER");
        ORDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORDERActionPerformed(evt);
            }
        });
        jPanel3.add(ORDER);
        ORDER.setBounds(370, 10, 80, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(463, 10, 90, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(280, 120, 560, 50);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Makanan", "Nama Minuman", "Harga Makanan", "Harga Minuman"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 520, 180);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(280, 180, 560, 200);

        setBounds(0, 0, 868, 436);
    }// </editor-fold>//GEN-END:initComponents

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:
        NamaMakanan.setText("");
        NamaMinuman.setText("");
        HargaMakanan.setText("");
        HargaMinuman.setText("");
    }//GEN-LAST:event_CLEARActionPerformed

    private void ORDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORDERActionPerformed
        // TODO add your handling code here:
        new Order().show();
        this.dispose();
    }//GEN-LAST:event_ORDERActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:z
        /*if(NamaMakanan.getText().equals("") || HargaMakanan.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data Sepasang atau Seluruhnya", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (NamaMinuman.getText().equals("") || HargaMinuman.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data Sepasang atau Seluruhnya", "Error", JOptionPane.WARNING_MESSAGE);
        } else*/ if (NamaMakanan.getText().equals("") || HargaMakanan.getText().equals("") || NamaMinuman.getText().equals("") || HargaMinuman.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
        /*String SQL = "INSERT INTO t_barang(nama_makanan,nama_minuman,harga_makanan,harga_minuman)"+
            "VALUES('"+NamaMakanan.getText()+"','"+NamaMinuman.getText()+"','"+HargaMakanan.getText()+"','"+HargaMinuman.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this,"Menu berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else{
                JOptionPane.showMessageDialog(this,"Menu gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
            }*/
        String SQL = "INSERT INTO tb_makanan VALUES ('"+NamaMakanan.getText()+"', '"+NamaMinuman.getText()+"', '"+HargaMakanan.getText()+"', '"+HargaMinuman.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Menu Berhasil Ditambahkan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Menu Gagal Ditambahkan", "GAGAL", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_SAVEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        int baris = Table1.getSelectedRow();
        if (baris != -1) {
            String NamaMakanan = Table1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_makanan WHERE NIS='"+NamaMakanan+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Menu berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, "Menu gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DELETEActionPerformed

    private void PRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINTActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Menu Makanan Resto NEW MOON");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)   ");
        
        try {
            Table1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_PRINTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField HargaMakanan;
    private javax.swing.JTextField HargaMinuman;
    private javax.swing.JTextField NamaMakanan;
    private javax.swing.JTextField NamaMinuman;
    private javax.swing.JButton ORDER;
    private javax.swing.JButton PRINT;
    private javax.swing.JButton SAVE;
    private javax.swing.JTable Table1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Nama Makanan","Nama Minuman","Harga Makanan","Harga Minuman"};
        DefaultTableModel dtm = new DefaultTableModel (null, kolom);
        String SQL = "SELECT * FROM tb_makanan";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String NamaMakanan = rs.getString(1);
                String NamaMinuman = rs.getString(2);
                String HargaMakanan = rs.getString(3);
                String HargaMinuman = rs.getString(4);
                String data[] = {NamaMakanan,NamaMinuman,HargaMakanan,HargaMinuman};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        Table1.setModel(dtm);
    }
}
